import { About, Hero, Navbar, Skills, Projects } from '@/components';
import Head from 'next/head';

const Home = () => {
   return (
      <>
         <Head>
            <title>Ehsan | Front-End Developer</title>
            <meta name="description" content="Generated by Ehsan Saraee" />
            <link rel="icon" href="/assets/Logo_6.png" />
         </Head>
         <Navbar />
         <Hero />
         <About />
         <Skills />
         <Projects />
      </>
   );
};

export default Home;
