import Hero from '@/components/Hero';
import Navbar from '@/components/Navbar';
import Head from 'next/head';

const Home = () => {
   return (
      <>
         <Head>
            <title>Ehsan | Front-End Developer</title>
            <meta name="description" content="Generated by Ehsan Saraee" />
            <link rel="icon" href="/assets/Logo_6.png" />
         </Head>
         <Navbar />
         <Hero />
      </>
   );
};

export default Home;
